package com.mantenimiento.AutoAlDiaBackend.model.enums;

public enum TipoServicio {
    CAMBIO_ACEITE,
    CAMBIO_FILTRO_ACEITE,
    CAMBIO_FILTRO_AIRE,
    CAMBIO_FILTRO_COMBUSTIBLE,
    NEUMATICOS,
    ALINEACION_BALANCEO,
    FRENOS,
    BATERIA,
    BUJIAS,
    CORREA_DISTRIBUCION,
    LIQUIDO_FRENOS,
    REFRIGERANTE,
    TRANSMISION,
    SUSPENSION,
    AIRE_ACONDICIONADO,
    REVISION_GENERAL,
    REPARACION_MOTOR,
    REPARACION_ELECTRICA,
    CHAPA_PINTURA,
    OTRO

}
